/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmpe331_project;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author selinyesilselve
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        teacher_anc_scrool.setVisible(false);
        //teacher_anc.setVisible(false);
        add_annc.setVisible(false);
        add_homework.setVisible(false);
        jScrollPane5.setVisible(false);
        updatebutton.setVisible(false);
        exam_schedule_scrool.setVisible(false);
        add_schedule.setVisible(false);
        grade_id.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacher_photo = new javax.swing.JLabel();
        teacher_name = new javax.swing.JLabel();
        teacher_id = new javax.swing.JLabel();
        teacher_type = new javax.swing.JLabel();
        Genel = new javax.swing.JTabbedPane();
        Classlists = new javax.swing.JPanel();
        classList_class_comboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacher_classlist = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        classList_select = new javax.swing.JButton();
        Homework = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        teacher_homework = new javax.swing.JTable();
        create_hw = new javax.swing.JButton();
        add_homework = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        teacher_hw_show = new javax.swing.JTable();
        hw_refresh = new javax.swing.JButton();
        hw_delete = new javax.swing.JButton();
        ExamSchedule = new javax.swing.JPanel();
        exam_schedule_scrool = new javax.swing.JScrollPane();
        exam_schedule = new javax.swing.JTable();
        create_schedule = new javax.swing.JButton();
        add_schedule = new javax.swing.JButton();
        refresh_schedule = new javax.swing.JButton();
        delete_schedule = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        exam_schedule_show = new javax.swing.JTable();
        GradeInfo = new javax.swing.JPanel();
        comboBoxClass = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboBoxLecture = new javax.swing.JComboBox<>();
        gradebookselectbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        gradebooktable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        grade_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        grade_midterm = new javax.swing.JTextField();
        grade_project = new javax.swing.JTextField();
        grade_final = new javax.swing.JTextField();
        add_annc = new javax.swing.JButton();
        create_anc = new javax.swing.JButton();
        teacher_anc_scrool = new javax.swing.JScrollPane();
        teacher_anc = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        teacher_annc_show = new javax.swing.JTable();
        refresh_button = new javax.swing.JButton();
        delete_anc = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        teacher_out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teacher_photo.setText("teacher_photo");

        teacher_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        teacher_name.setText("Teacher_name");

        teacher_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        teacher_id.setText("t_id");

        teacher_type.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        teacher_type.setText("t_type");

        Genel.setBackground(new java.awt.Color(51, 255, 102));
        Genel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenelMouseClicked(evt);
            }
        });

        classList_class_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4/A", "4/B" }));

        teacher_classlist.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        teacher_classlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Last Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teacher_classlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacher_classlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(teacher_classlist);

        jLabel2.setText("Select your class:");

        classList_select.setText("Select");
        classList_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classList_selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClasslistsLayout = new javax.swing.GroupLayout(Classlists);
        Classlists.setLayout(ClasslistsLayout);
        ClasslistsLayout.setHorizontalGroup(
            ClasslistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClasslistsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(classList_class_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(classList_select)
                .addGap(51, 51, 51))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        ClasslistsLayout.setVerticalGroup(
            ClasslistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClasslistsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClasslistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classList_class_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classList_select)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Genel.addTab("ClassList", Classlists);

        teacher_homework.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(teacher_homework);

        create_hw.setText("createHomework");
        create_hw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_hwActionPerformed(evt);
            }
        });

        add_homework.setText("Add Homework");
        add_homework.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_homeworkActionPerformed(evt);
            }
        });

        teacher_hw_show.setBackground(new java.awt.Color(255, 204, 153));
        teacher_hw_show.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        teacher_hw_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Homework", "Deadline", "Lecture Name", "Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(teacher_hw_show);

        hw_refresh.setText("Refresh");
        hw_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hw_refreshActionPerformed(evt);
            }
        });

        hw_delete.setText("Delete");
        hw_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hw_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeworkLayout = new javax.swing.GroupLayout(Homework);
        Homework.setLayout(HomeworkLayout);
        HomeworkLayout.setHorizontalGroup(
            HomeworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeworkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(HomeworkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeworkLayout.createSequentialGroup()
                        .addComponent(hw_refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_homework, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomeworkLayout.createSequentialGroup()
                        .addComponent(hw_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(create_hw)))
                .addContainerGap())
        );
        HomeworkLayout.setVerticalGroup(
            HomeworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hw_refresh)
                    .addComponent(add_homework, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(HomeworkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeworkLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(hw_delete))
                    .addGroup(HomeworkLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(create_hw)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        Genel.addTab("Homework", Homework);

        exam_schedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        exam_schedule_scrool.setViewportView(exam_schedule);

        create_schedule.setText("Create an exam date");
        create_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_scheduleActionPerformed(evt);
            }
        });

        add_schedule.setText("Add an exam date");
        add_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_scheduleActionPerformed(evt);
            }
        });

        refresh_schedule.setText("Refresh");
        refresh_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_scheduleActionPerformed(evt);
            }
        });

        delete_schedule.setText("Delete");
        delete_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_scheduleActionPerformed(evt);
            }
        });

        exam_schedule_show.setBackground(new java.awt.Color(204, 255, 204));
        exam_schedule_show.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        exam_schedule_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecture Name", "Date "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(exam_schedule_show);

        javax.swing.GroupLayout ExamScheduleLayout = new javax.swing.GroupLayout(ExamSchedule);
        ExamSchedule.setLayout(ExamScheduleLayout);
        ExamScheduleLayout.setHorizontalGroup(
            ExamScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExamScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refresh_schedule)
                    .addComponent(delete_schedule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ExamScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_schedule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_schedule, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExamScheduleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exam_schedule_scrool, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        ExamScheduleLayout.setVerticalGroup(
            ExamScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExamScheduleLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ExamScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExamScheduleLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(refresh_schedule)
                        .addGap(18, 18, 18)
                        .addComponent(delete_schedule)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ExamScheduleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(add_schedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(create_schedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(exam_schedule_scrool, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        Genel.addTab("Exam Schedule", ExamSchedule);

        comboBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4/A", "4/B" }));

        jLabel8.setText("Select your class:");

        jLabel9.setText("Lecture");

        gradebookselectbutton.setText("Select");
        gradebookselectbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradebookselectbuttonActionPerformed(evt);
            }
        });

        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        gradebooktable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gradebooktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Lastname", "Midterm", "Final", "Project", "Average"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradebooktable.setToolTipText("");
        gradebooktable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradebooktableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(gradebooktable);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Student ID:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Midterm: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Final: ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Project:");

        javax.swing.GroupLayout GradeInfoLayout = new javax.swing.GroupLayout(GradeInfo);
        GradeInfo.setLayout(GradeInfoLayout);
        GradeInfoLayout.setHorizontalGroup(
            GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addGroup(GradeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradeInfoLayout.createSequentialGroup()
                        .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GradeInfoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grade_project, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grade_final, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grade_midterm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(GradeInfoLayout.createSequentialGroup()
                                        .addComponent(grade_id, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(updatebutton))))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(GradeInfoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addComponent(comboBoxLecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gradebookselectbutton)
                        .addGap(79, 79, 79))))
        );
        GradeInfoLayout.setVerticalGroup(
            GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradeInfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradebookselectbutton)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxLecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(updatebutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(grade_midterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(grade_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GradeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(grade_project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        Genel.addTab("Grade Info", GradeInfo);

        add_annc.setText("Add Announcement");
        add_annc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_anncActionPerformed(evt);
            }
        });

        create_anc.setText("Create Announcement");
        create_anc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_ancActionPerformed(evt);
            }
        });

        teacher_anc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        teacher_anc_scrool.setViewportView(teacher_anc);

        teacher_annc_show.setBackground(new java.awt.Color(204, 255, 102));
        teacher_annc_show.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        teacher_annc_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Announcement", "Teacher Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(teacher_annc_show);

        refresh_button.setText("Refresh");
        refresh_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_buttonActionPerformed(evt);
            }
        });

        delete_anc.setText("Delete");
        delete_anc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ancActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("NAME : ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("ID :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("PROFESSION:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");

        teacher_out.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        teacher_out.setText("Sign Out");
        teacher_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacher_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(teacher_name)
                                            .addComponent(teacher_id)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(teacher_type))))
                            .addComponent(jLabel10))
                        .addGap(169, 169, 169)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 674, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teacher_out)
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Genel, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refresh_button)
                            .addComponent(delete_anc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_annc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create_anc)
                            .addComponent(teacher_anc_scrool, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(teacher_out)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(teacher_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(teacher_id)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacher_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(teacher_type, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(Genel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(refresh_button)
                        .addGap(18, 18, 18)
                        .addComponent(delete_anc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_annc)
                        .addGap(18, 18, 18)
                        .addComponent(create_anc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teacher_anc_scrool, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_anncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_anncActionPerformed
       
        try {
            // TODO add your handling code here:
            MyFunctions.addTeacherAnnouncement(teacher_anc);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
    }//GEN-LAST:event_add_anncActionPerformed

    private void create_ancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_ancActionPerformed
         //teacher_anc_scrool.setVisible(true);
        // teacher_anc.setVisible(true);
         add_annc.setVisible(true);
           try {
            // TODO add your handling code here:
        //    jScrollPane4.setVisible(true);
            MyFunctions.createTeacherAnnouncement(teacher_anc);
            create_anc.setVisible(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_create_ancActionPerformed

    private void refresh_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_buttonActionPerformed
        try {
            // TODO add your handling code here:
           

            DefaultTableModel model = (DefaultTableModel) teacher_annc_show.getModel();
            model.setRowCount(0);
            MyFunctions.studentAnnouncement(teacher_annc_show);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refresh_buttonActionPerformed

    private void delete_ancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ancActionPerformed
        try {
            // TODO add your handling code here:
            MyFunctions.deleteAnnouncement(teacher_annc_show);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_ancActionPerformed

    private void GenelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenelMouseClicked

    }//GEN-LAST:event_GenelMouseClicked

    private void hw_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hw_deleteActionPerformed
        try {
            // TODO add your handling code here:
            MyFunctions.deleteHomework(teacher_hw_show);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hw_deleteActionPerformed

    private void hw_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hw_refreshActionPerformed

        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) teacher_hw_show.getModel();
            model.setRowCount(0);
            MyFunctions.homeworkShow(teacher_hw_show);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hw_refreshActionPerformed

    private void add_homeworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_homeworkActionPerformed
        try {
            // TODO add your handling code here:
            MyFunctions.addTeacherHomework(teacher_homework);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_homeworkActionPerformed

    private void create_hwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_hwActionPerformed
        try {
            // TODO add your handling code here:
            add_homework.setVisible(true);
            MyFunctions.createTeacherHomework(teacher_homework);
            create_hw.setVisible(false );
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_create_hwActionPerformed

    private void classList_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classList_selectActionPerformed
        try {
            // TODO add your handling code here:,,
            MyFunctions.studentList(teacher_classlist, classList_class_comboBox);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_classList_selectActionPerformed

    private void teacher_classlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher_classlistMouseClicked
        try {
            // TODO add your handling code here:
            MyFunctions.studentInfo(teacher_classlist);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_teacher_classlistMouseClicked

    private void gradebooktableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradebooktableMouseClicked
        // TODO add your handling code here:

        int selectedRow = gradebooktable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) gradebooktable.getModel();

        grade_id.setText(model.getValueAt(selectedRow, 0).toString());
        grade_midterm.setText(model.getValueAt(selectedRow, 3).toString());
        grade_final.setText(model.getValueAt(selectedRow, 4).toString());
        grade_project.setText(model.getValueAt(selectedRow, 5).toString());

    }//GEN-LAST:event_gradebooktableMouseClicked
    
    public static int a_midterm;
    public static int a_final;
    public static int a_project;
    public static String a_id;
    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        try {
             a_midterm = Integer.valueOf(grade_midterm.getText());
             a_final = Integer.valueOf(grade_final.getText());
             a_project = Integer.valueOf(grade_project.getText());
             a_id = grade_id.getText();
             
            MyFunctions.gradeInfoUpdate(gradebooktable,comboBoxLecture);
            
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_updatebuttonActionPerformed

    private void gradebookselectbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradebookselectbuttonActionPerformed
        try {
            // TODO add your handling code here:
            MyFunctions.studentGradebookInformation(gradebooktable, comboBoxLecture,comboBoxClass);
            updatebutton.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        updatebutton.setVisible(true);
    }//GEN-LAST:event_gradebookselectbuttonActionPerformed

    private void create_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_scheduleActionPerformed
        try {
            // TODO add your handling code here:

            MyFunctions.createExamSchedule(exam_schedule);
            add_schedule.setVisible(true);
            create_schedule.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_create_scheduleActionPerformed

    private void add_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_scheduleActionPerformed
        try {
            // TODO add your handling code here:
            MyFunctions.addExamDate(exam_schedule);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_scheduleActionPerformed

    private void refresh_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_scheduleActionPerformed
        // TODO add your handling code here:
        try {
        DefaultTableModel model = (DefaultTableModel) exam_schedule_show.getModel();
            model.setRowCount(0);
        
            MyFunctions.scheduleShow(exam_schedule_show);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_refresh_scheduleActionPerformed

    private void delete_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_scheduleActionPerformed
        try {
            // TODO add your handling code here:
            MyFunctions.deleteSchedule(exam_schedule_show);
        } catch (SQLException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_scheduleActionPerformed

    private void teacher_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_outActionPerformed
        // TODO add your handling code here:
        
         //new Login_Part().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_teacher_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Classlists;
    public javax.swing.JPanel ExamSchedule;
    public javax.swing.JTabbedPane Genel;
    public javax.swing.JPanel GradeInfo;
    public javax.swing.JPanel Homework;
    public javax.swing.JButton add_annc;
    public javax.swing.JButton add_homework;
    public javax.swing.JButton add_schedule;
    public javax.swing.JComboBox<String> classList_class_comboBox;
    public javax.swing.JButton classList_select;
    public javax.swing.JComboBox<String> comboBoxClass;
    public javax.swing.JComboBox<String> comboBoxLecture;
    public javax.swing.JButton create_anc;
    public javax.swing.JButton create_hw;
    public javax.swing.JButton create_schedule;
    public javax.swing.JButton delete_anc;
    public javax.swing.JButton delete_schedule;
    private javax.swing.JTable exam_schedule;
    public javax.swing.JScrollPane exam_schedule_scrool;
    public javax.swing.JTable exam_schedule_show;
    public javax.swing.JTextField grade_final;
    public javax.swing.JTextField grade_id;
    public javax.swing.JTextField grade_midterm;
    public javax.swing.JTextField grade_project;
    public javax.swing.JButton gradebookselectbutton;
    public javax.swing.JTable gradebooktable;
    public javax.swing.JButton hw_delete;
    public javax.swing.JButton hw_refresh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JButton refresh_button;
    public javax.swing.JButton refresh_schedule;
    public javax.swing.JTable teacher_anc;
    public javax.swing.JScrollPane teacher_anc_scrool;
    public javax.swing.JTable teacher_annc_show;
    public javax.swing.JTable teacher_classlist;
    public javax.swing.JTable teacher_homework;
    public javax.swing.JTable teacher_hw_show;
    public javax.swing.JLabel teacher_id;
    public javax.swing.JLabel teacher_name;
    private javax.swing.JButton teacher_out;
    public javax.swing.JLabel teacher_photo;
    public javax.swing.JLabel teacher_type;
    public javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
